// export const scheduleData = {
//   SUN: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10:30 AM",
//       group: ["L4CG4"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "11:00 AM to 1:30 PM",
//       group: ["L4CG1"],
//       room: "SR - 01 Wolves",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "11:30 AM to 2:00 PM",
//       group: ["L4CG2"],
//       room: "SR - 02 Compton",
//     },
//     {
//       classType: "Lecture",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "12 PM to 2 PM",
//       group: ["L4CG3", "L4CG4"],
//       room: "LT - 01 Wulfurna",
//     },
//   ],
//   MON: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "8 AM to 10 AM",
//       group: ["L4CG3"],
//       room: "SR - 01 Wolves",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "8 AM to 10:30 AM",
//       group: ["L4CG4"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Lecture",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "12 PM to 2 PM",
//       group: ["L4CG3", "L4CG4"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "11:00 AM to 1:00 PM",
//       group: ["L4CG1"],
//       room: "SR - 01 Wolves",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "12:00 PM to 2:30 PM",
//       group: ["L4CG2"],
//       room: "SR - 02 Compton",
//     },
//   ],
//   TUE: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10 AM",
//       group: ["L4CG3"],
//       room: "SR - 01 Wolves",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "8 AM to 10 AM",
//       group: ["L4CG4"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Lecture",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "12 PM to 2 PM",
//       group: ["L4CG3", "L4CG4"],
//       room: "LT - 01 Wulfurna",
//     },
//   ],
//   WED: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10:30 AM",
//       group: ["L4CG3"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "11 AM to 1:30 PM",
//       group: ["L4CG2"],
//       room: "SR - 02 Compton",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "12 PM to 2 PM",
//       group: ["L4CG3"],
//       room: "SR - 01 Wolves",
//     },
//   ],
//   THU: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "8 AM to 10:30 AM",
//       group: ["L4CG3"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "11 AM to 1 PM",
//       group: ["L4CG4"],
//       room: "SR - 01 Wolves",
//     },
//     {
//       classType: "Lecture",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "12 PM to 2 PM",
//       group: ["L4CG1", "L4CG4"],
//       room: "LT - 01 Wulfurna",
//     },
//   ],
//   FRI: [
//     {
//       classType: "Lecture",
//       moduleCode: "4CS001",
//       moduleTitle: "Introductory Programming and Problem Solving",
//       lecturer: "Mr. Basanta Singh",
//       time: "8 AM to 10 AM",
//       group: ["L4CG1", "L4CG3"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Workshop",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "8 AM to 10:30 AM",
//       group: ["L4CG4"],
//       room: "LAB - 01 Baraha",
//     },
//     {
//       classType: "Lecture",
//       moduleCode: "4CS017",
//       moduleTitle: "Internet Software Architecture and Database",
//       lecturer: "Mr. Arvind Nepal",
//       time: "11 AM to 1 PM",
//       group: ["L4CG2"],
//       room: "LT - 01 Wulfurna",
//     },
//     {
//       classType: "Tutorial",
//       moduleCode: "4CS015",
//       moduleTitle: "Fundamentals of Computing",
//       lecturer: "Mr. Sanjeev Chamling",
//       time: "12 PM to 2 PM",
//       group: ["L4CG3"],
//       room: "SR - 01 Wolves",
//     },
//   ],
// };
export const scheduleData = {
  SUN: [
    {
      Day: "SUN",
      Time: "8 AM to 10 AM",
      "Class Type": "Lecture",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG1+L4CG2",
      Room: "LT - 01 Wulfurna",
    },
    {
      Day: "SUN",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG4",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "SUN",
      Time: "11:00 AM to 1:30 PM",
      "Class Type": "Workshop",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG1",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "SUN",
      Time: "11:30 AM to 2:00 PM",
      "Class Type": "Workshop",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG2",
      Room: "SR - 02 Compton",
    },
    {
      Day: "SUN",
      Time: "12 PM to 2 PM",
      "Class Type": "Lecture",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG3 + L4CG4",
      Room: "LT - 01 Wulfurna",
    },
  ],
  MON: [
    {
      Day: "MON",
      Time: "8 AM to 10 AM",
      "Class Type": "Lecture",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG1+L4CG2",
      Room: "LT - 01 Wulfurna",
    },
    {
      Day: "MON",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG3",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "MON",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG4",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "MON",
      Time: "12 PM to 2 PM",
      "Class Type": "Lecture",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG3 + L4CG4",
      Room: "LT - 01 Wulfurna",
    },
    {
      Day: "MON",
      Time: "11:00 AM to 1:00 PM",
      "Class Type": "Tutorial",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG1",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "MON",
      Time: "12:00 PM to 2:30 PM",
      "Class Type": "Workshop",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG2",
      Room: "SR - 02 Compton",
    },
  ],
  TUE: [
    {
      Day: "TUE",
      Time: "8 AM to 10 AM",
      "Class Type": "Lecture",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG1+L4CG2",
      Room: "LT - 01 Wulfurna",
    },
    {
      Day: "TUE",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG3",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "TUE",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG4",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "TUE",
      Time: "12 PM to 2 PM",
      "Class Type": "Lecture",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG3 + L4CG4",
      Room: "LT - 01 Wulfurna",
    },
  ],
  WED: [
    {
      Day: "WED",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG2",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "WED",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG1",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "WED",
      Time: "9 AM to 11 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG3",
      Room: "SR - 02 Compton",
    },
    {
      Day: "WED",
      Time: "11:30 AM to 1:30 PM",
      "Class Type": "Tutorial",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG2",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "WED",
      Time: "12 PM to 2 PM",
      "Class Type": "Tutorial",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG4",
      Room: "LAB - 01 Baraha",
    },
  ],
  THU: [
    {
      Day: "THU",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG1",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "THU",
      Time: "8 AM to 10 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG4",
      Room: "SR - 02 Compton",
    },
    {
      Day: "THU",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG2",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "THU",
      Time: "11 PM to 1 PM",
      "Class Type": "Tutorial",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG1",
      Room: "SR - 02 Compton",
    },
    {
      Day: "THU",
      Time: "11:30 AM to 2 PM",
      "Class Type": "Workshop",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG3",
      Room: "LAB - 01 Baraha",
    },
  ],
  FRI: [
    {
      Day: "FRI",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG3",
      Room: "SR - 01 Wolves",
    },
    {
      Day: "FRI",
      Time: "8 AM to 10:30 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG1",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "FRI",
      Time: "11:00 AM to 1:30 PM",
      "Class Type": "Workshop",
      "Module Code": "4CS001",
      "Module Title": "Introductory Programming and Problem Solving",
      Lecturer: "Mr. Basanta Singh",
      Group: "L4CG4",
      Room: "LAB - 01 Baraha",
    },
    {
      Day: "FRI",
      Time: "11:30 AM to 1:30 AM",
      "Class Type": "Tutorial",
      "Module Code": "4CS017",
      "Module Title": "Internet Software Architecture and Database",
      Lecturer: "Mr. Arvind Nepal",
      Group: "L4CG2",
      Room: "SR - 02 Compton",
    },
    {
      Day: "FRI",
      Time: "11:30 AM to 2:00 AM",
      "Class Type": "Workshop",
      "Module Code": "4CS015",
      "Module Title": "Fundamentals of Computing",
      Lecturer: "Mr. Sanjeev Chamling",
      Group: "L4CG3",
      Room: "SR - 01 Wolves",
    },
  ],
};
